name: get_cli
version: 1.8.4
homepage: https://github.com/jonataslaw/get_cli
description: Official CLI for GetXâ„¢ framework to build Flutter and Server
  Applications easily
environment:
  sdk: ">=2.18.0 <3.0.0"

dependency_overrides:
  _fe_analyzer_shared: ^58.0.0

dependencies:
  #  archive: ^3.1.2
  ansicolor: ^2.0.1
  collection: ^1.17.1
  dart_style: ^2.0.1
  dcli: ^2.1.0
  http: ^0.13.5
  intl: ^0.18.0
  path: ^1.8.3
  process_run: ^0.12.5+3
  pubspec: ^2.3.0
  recase: ^4.1.0
  version: ^3.0.2
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1

executables:
  get: get
  getx: get
